name: SonarCloud Analysis

on:
  push:
    branches:
      - main
      - master
      - develop
      - feature
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'

      # 1. Compilamos Y ejecutamos los Unit Tests (testDebugUnitTest es el estándar de Android)
      - name: Build and Run Tests
        run: ./gradlew assembleDebug testDebugUnitTest

      # 2. Escaneamos con Sonar indicándole dónde están los reportes de los tests
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=lsk-llopez_com-lksnext-parkingllopez
            -Dsonar.organization=lsk-llopez
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.sources=app/src/main/java
            -Dsonar.tests=app/src/test/java
            -Dsonar.java.binaries=app/build/tmp/kotlin-classes/debug
            -Dsonar.junit.reportPaths=app/build/test-results/testDebugUnitTest